return {
  "pojokcodeid/cheatsheet-nvim",
  event = "VeryLazy",
  keys = {
    { "<F1>", "<cmd>KeymapsPopup<cr>", desc = "Keymaps Popup" },
    { "<leader>?", "<cmd>KeymapsPopup<cr>", desc = "Cheatsheet Popup" },
  },
  cmd = { "KeymapsPopup" },
  opts = {
    ["PENTING"] = {
      { "Copy", "n/v/x", "<C-c> (system clipboard), yy (line)" },
      { "Paste", "n/v/x", "<C-v>" },
      { "Cut", "n/v", "dd (line), d (selection/motion)" },
      { "Delete", "n/v", "x (char), d (selection/motion)" },
      { "Block", "n", "<C-v> (visual block), v/V (visual)" },
      { "Undo", "n/i/v/x", "<C-z> atau u" },
      { "Redo", "n", "<C-r>" },
      { "Ke line kanan", "n", "l atau <Right>" },
      { "Ke line kiri", "n", "h atau <Left>" },
      { "Pindah blok kode ke atas", "x", "<A-Up>" },
      { "Pindah blok kode ke bawah", "x", "<A-Down>" },
      { "Duplicate blok kode ke atas", "x", "<S-Up> atau <S-M-Up>" },
      { "Duplicate blok kode ke bawah", "x", "<S-Down> atau <S-M-Down>" },
      { "Cari kata di 1 file", "n", "<leader>/ (current buffer), /" },
      { "Cari kata di seluruh file", "n", "<leader>F (Telescope live_grep)" },
      { "Cari file/folder (fuzzy)", "n", "<leader><leader> (Telescope find_files)" },
      { "Terminal bawah", "n", "<leader>th" },
      { "Terminal float", "n", "<leader>tf" },
    },
    ["Main Shortcuts"] = {
      { "Cheatsheet Popup", "n", "<leader>? atau F1" },
      { "Quit Neovim", "n", "q" },
      { "Toggle NvimTree + focus file", "n", "f" },
      { "Save File", "i/v/n/x", "<C-s>" },
      { "Comment Line", "n/i", "<C-_>" },
      { "Comment Selection", "v/x", "<C-/> atau <C-_>" },
      { "Open live-server terminal", "n", "<A-l>" },
      { "Gemini Chat", "n", "<leader>ga" },
    },
    ["AI Assistants (Gemini & Opencode)"] = {
      { "Gemini Chat", "n/v/x", "<leader>ga atau <C-i>" },
      { "Opencode Terminal", "n/v/x", "<leader>ot atau <C-o>" },
      { "Opencode Ask Cursor", "n", "<leader>oa" },
      { "Opencode Ask Selection", "v", "<leader>oa" },
      { "Opencode Explain Code", "n", "<leader>oe" },
      { "Opencode New Session", "n", "<leader>on" },
      { "Opencode Select Prompt", "n/v", "<leader>os" },
    },
    ["Windows & Navigation"] = {
      { "Window left", "n", "<C-h>" },
      { "Window down", "n", "<C-j>" },
      { "Window up", "n", "<C-k>" },
      { "Window right", "n", "<C-l>" },
      { "Next Buffer", "n", "<S-l> atau <S-Left>" },
      { "Previous Buffer", "n", "<S-h> atau <S-Right>" },
      { "Move buffer left", "n", "<S-PageUp>" },
      { "Move buffer right", "n", "<S-PageDown>" },
      { "Close current buffer", "n", "<C-w>" },
    },
    ["Editing & Row Manipulation"] = {
      { "Duplicate line down", "i/v/n/x", "<S-Down> atau <S-M-Down>" },
      { "Duplicate line up", "i/v/n/x", "<S-Up> atau <S-M-Up>" },
      { "Move line down", "n/i", "<M-Down>" },
      { "Move line up", "n/i", "<M-Up>" },
      { "Move selected block down", "x", "<A-Down>" },
      { "Move selected block up", "x", "<A-Up>" },
      { "Indent left/right (stay selection)", "v", "< / >" },
      { "Exit insert mode", "i", "jk atau kj" },
    },
    ["Clipboard & Selection"] = {
      { "Select all", "n", "<C-a>" },
      { "Select all from insert", "i", "<C-a>" },
      { "Copy to system clipboard", "n/v/x", "<C-c>" },
      { "Paste from system clipboard", "n/v/x", "<C-v>" },
      { "Paste from insert mode", "i", "<C-v>" },
      { "Undo", "n/i/v/x", "<C-z>" },
    },
    ["Git ( <leader>g )"] = {
      { "Lazygit", "n", "<leader>gg" },
      { "Next/Prev Hunk", "n", "<leader>gj / <leader>gk" },
      { "Blame Line", "n", "<leader>gl" },
      { "Preview Hunk", "n", "<leader>gp" },
      { "Reset Hunk/Buffer", "n", "<leader>gr / <leader>gR" },
      { "Git Status", "n", "<leader>go" },
      { "Git Branches", "n", "<leader>gb" },
      { "Git Commits", "n", "<leader>gc" },
      { "Git Diff", "n", "<leader>gd" },
    },
    ["LSP ( <leader>l )"] = {
      { "LSP Code Action", "n", "<leader>la" },
      { "LSP Code Format", "n", "<leader>lf atau <leader>lF" },
      { "LSP Information", "n", "<leader>li" },
      { "Mason Information", "n", "<leader>lI" },
      { "LSP Rename", "n", "<leader>lr" },
      { "LSP Next/Prev Diagnostic", "n", "<leader>lj / <leader>lk" },
      { "LSP Signature Help", "n", "<leader>ls" },
    },
    ["Search ( <leader>s )"] = {
      { "Find Help", "n", "<leader>sh" },
      { "Colorscheme", "n", "<leader>sc" },
      { "Recent Files", "n", "<leader>sr" },
      { "Registers", "n", "<leader>sR" },
      { "Keymaps", "n", "<leader>sk" },
      { "Commands", "n", "<leader>sC" },
    },
    ["Terminal ( <leader>t )"] = {
      { "Float Terminal", "n", "<leader>tf" },
      { "Horizontal Terminal", "n", "<leader>th" },
      { "Vertical Terminal", "n", "<leader>tv" },
      { "New Tab Terminal", "n", "<leader>ts" },
      { "Close All Terminals", "n", "<leader>tx" },
    },
    ["Run & Test ( <leader>r / <leader>T )"] = {
      { "Run Code", "n", "<leader>rr" },
      { "Run File", "n", "<leader>rf" },
      { "Run Project", "n", "<leader>rp" },
      { "Test Nearest", "n", "<leader>Tn" },
      { "Test File", "n", "<leader>Tt" },
      { "Test Summary", "n", "<leader>Ts" },
    },
    ["Others"] = {
      { "Treesitter uninstall picker", "cmd", ":TSIsInstalled" },
      { "Leader key", "all", "<Space>" },
    },
  },

  config = true,
}
